// src/11-delete-a-todo/vue/TodoPage.vue
<script setup lang="ts">
  import { onMounted, onUnmounted } from 'vue'
  import { signalRef } from '@/7-vue-app/signalRef'
  import RemoteData from '@/7-vue-app/RemoteData.vue'
  import TodoCheckboxList from './TodoCheckboxList.vue'
  import { TodoPageModel } from '../TodoPageModel'
  import ConfirmActionDialog from './ConfirmActionDialog.vue'

  const props = defineProps<{ model: TodoPageModel }>()
  const model = props.model

  const todoList = signalRef(model.getTodoList.data)
  const canPatchAnyTodo = signalRef(model.canPatchAnyTodo)

  // fetch the todos on mount.
  onMounted(() => void model.getTodoList.trigger())

  onUnmounted(model.dispose)
</script>

<template>
  <div>
    <p>Todo Page in Vue</p>

    <ConfirmActionDialog :action="model.deleteTodo">
      <template #default="{ value: [todo] }">
        You are about to delete "{{ todo.title }}", continue?
      </template>
    </ConfirmActionDialog>
    
    <RemoteData :data="todoList">
      <template #success="{ value }">
        <TodoCheckboxList
          :todos="value"
          :disabled="!canPatchAnyTodo"
          @toggle="model.toggleTodo"
          @title-changed="model.changeTodoTitle"
          @delete="(todo) => model.deleteTodo.ask(todo)"
        />
      </template>
    </RemoteData>
  </div>
</template>

// src/11-delete-a-todo/react/TodoPage.tsx
/** @jsx React.createElement */
import React from 'react'
import { RemoteData } from '@/6-react-app/RemoteData'
import { useSignal } from '@/6-react-app/useSignal'
import { useEffect } from "react"
import { TodoPageModel } from '../TodoPageModel'
import { TodoCheckboxList } from "./TodoCheckboxList"
import { ConfirmActionDialog } from './ConfirmActionDialog'

interface Props {
  model: TodoPageModel
}

export function TodoPage({ model }: Props) {
  const todoList = useSignal(model.getTodoList.data)
  const canPatchAnyTodo = useSignal(model.canPatchAnyTodo)

  // fetch the todo list on mount.
  useEffect(() => {
    void model.getTodoList.trigger()
    // explicitly mark the promise as non-awaiting with `void`
  }, [])

  // dispose on unmount.
  useEffect(() => model.dispose, [])

  return (
    <div>
      <p>Todo Page in React</p>

      <ConfirmActionDialog action={model.deleteTodo}>
        {(todo) => <>You are about to delete "{todo.title}", continue?</>}
      </ConfirmActionDialog>

      <RemoteData
        data={todoList}
        success={(todos) => (
          <TodoCheckboxList
            todos={todos}
            onToggle={model.toggleTodo}
            disabled={!canPatchAnyTodo}
            onTitleChanged={model.changeTodoTitle}
            onDelete={(todo) => model.deleteTodo.ask(todo)}
          />
        )}
      />
    </div>
  )
}
