// src/10-update-a-todo-title/react/TodoCheckboxList.tsx
/** @jsx React.createElement */
import React from "react"
import { Todo } from "../../setup/Api"

interface Props {
  todos: Todo[]
  onToggle: (todo: Todo) => unknown
  onTitleChanged: (todo: Todo, title: string) => unknown
  disabled: boolean
}
export function TodoCheckboxList({ todos, onToggle, onTitleChanged, disabled }: Props) {
  return (
    <div>
      {todos.map((todo) => (
        <div key={todo.id}>
          <input
            type="checkbox"
            checked={todo.completed}
            onChange={() => onToggle(todo)}
            disabled={disabled}
          />
          &emsp;
          <input
            type="text"
            disabled={disabled}
            defaultValue={todo.title} onBlur={((event) => {
              const nextTitle = event.target.value
              if (nextTitle === todo.title) return
              return onTitleChanged(todo, nextTitle)
            })}
          />
        </div>
      ))}
    </div>
  )
}

// src/10-update-a-todo-title/vue/TodoCheckboxList.vue
<script setup lang="ts">
  import { Todo } from '@/setup/Api'

  const props = defineProps<{
    todos: Todo[]
    disabled: boolean
  }>()
  const emit = defineEmits<{
    toggle: [todo: Todo]
    titleChanged: [todo: Todo, title: string]
  }>()

  function maybeEmitTitleChanged(todo: Todo, event: FocusEvent) {
    const nextTitle = (event.target as HTMLInputElement).value
    if (nextTitle === todo.title) return
    emit('titleChanged', todo, nextTitle)
  }
</script>

<template>
  <div>
    <div v-for="todo in props.todos">
      <input
        type="checkbox"
        :checked="todo.completed"
        :disabled="props.disabled"
        @change="emit('toggle', todo)"
      />
      &emsp;
      <input
        type="text"
        :value="todo.title"
        :disabled="props.disabled"
        @blur="(event) => maybeEmitTitleChanged(todo, event)"
      />
    </div>
  </div>
</template>
