// src/6-react-app/RemoteData.tsx
/** @jsx React.createElement */
import React from "react"
import { RemoteData } from "../setup/RemoteData"

interface Props<T> {
  data: RemoteData<T>
  initial?: () => React.ReactNode
  pending?: (progress?: number) => React.ReactNode
  failure?: (error: Error) => React.ReactNode
  success: (value: T) => React.ReactNode
}
export function RemoteData<T>({
  data,
  initial = () => <div>Waiting for data to be loaded</div>,
  pending = () => <div>Loading...</div>,
  failure = (error) => <div>Error: {error.message}</div>,
  success,
}: Props<T>) {
  return <>
    {data.state === 'initial' && initial()}
    {data.state === 'pending' && pending(data.progress)}
    {data.state === 'failure' && failure(data.error)}
    {data.state === 'success' && success(data.value)}
  </>
}

// src/7-vue-app/RemoteData.vue
<script setup lang="ts" generic="T">
  import { RemoteData } from '../setup/RemoteData'

  defineProps<{ data: RemoteData<T> }>()
</script>

<template>
  <slot v-if="data.state === 'initial'" name="initial">
    <p>Waiting for data to be loaded</p>
  </slot>

  <slot v-else-if="data.state === 'pending'" name="pending">
    <p>Loading…</p>
  </slot>

  <slot v-else-if="data.state === 'failure'" name="failure" :error="data.error">
    <p>Error: {{ data.error.message }}</p>
  </slot>

  <slot v-else name="success" :value="data.value"></slot>
</template>
