// src/6-react-app/TodoPage.tsx
/** @jsx React.createElement */
import React, { useEffect } from "react"
import { TodoPageModel } from "../5-app-model/TodoPageModel"
import { useSignal } from "./useSignal"
import { RemoteData } from "./RemoteData"
import { TodoUnorderedList } from "./TodoUnorderedList"

interface Props {
  model: TodoPageModel
}

export function TodoPage({ model }: Props) {
  const todos = useSignal(model.getTodoList.data)

  // fetch the todos on mount.
  useEffect(() => {
    void model.getTodoList.trigger()
    // explicitly mark the promise as non-awaited with `void`
  }, [])

  return (
    <div>
      <p>Todo Page in React</p>
      <RemoteData
        data={todos}
        success={(todos) => <TodoUnorderedList todos={todos} />}
      />
    </div>
  )
}

// src/7-vue-app/TodoPage.vue
<script setup lang="ts">
  import { onMounted } from 'vue'
  import { TodoPageModel } from '../5-app-model/TodoPageModel'
  import { signalRef } from './signalRef'
  import RemoteData from './RemoteData.vue'
  import TodoUnorderedList from './TodoUnorderedList.vue'

  const props = defineProps<{ model: TodoPageModel }>()
  const model = props.model

  const todos = signalRef(model.getTodoList.data)

  // fetch the todos on mount.
  onMounted(() => void model.getTodoList.trigger())
</script>

<template>
  <div>
    <p>Todo Page in Vue</p>
    <RemoteData :data="todos">
      <template #success="{ value }">
        <TodoUnorderedList :todos="value" />
      </template>
    </RemoteData>
  </div>
</template>
