// src/steps/step-6-react/App.tsx
/** @jsx React.createElement */
import React from "react"
import { AppModel } from "../../models/AppModel"
import { useSignal } from "./useSignal"
import { TodoPage } from "./TodoPage-2"

interface Props {
  model: AppModel
}

export function App({ model }: Props) {
  const activePage = useSignal(model.activePage)

  return (
    <>
      <p>React App</p>
      {activePage.name === "NotFound" && <p>Page Not Found</p>}
      {activePage.name === "Todos" && (
        <TodoPage model={activePage.createModel()} />
      )}
    </>
  )
}

// src/steps/step-7-vue/App.vue
<script setup lang="ts">
import { AppModel } from '../../models/AppModel'
import { signalRef } from './signalRef'
import TodoPage from './TodoPage.vue'

  const props = defineProps<{ model: AppModel }>()
  const model = props.model

  const activePage = signalRef(model.activePage)
</script>

<template>
  <p>Vue App</p>
  <p v-if="activePage.name === 'NotFound'">Page Not Found</p>
  <TodoPage
    v-if="activePage.name === 'Todos'"
    :model="activePage.createModel()"
  />
</template>
