// src/steps/step-6-react/TodoPage.tsx
/** @jsx React.createElement */
import React from 'react'
import { TodoPageModel } from '../../models/TodoPageModel'
import { TodoList } from './TodoList-2'

interface Props {
  model: TodoPageModel
}

export function TodoPage({ model }: Props) {
  return (
    <div>
      <p>Todo Page in React</p>
      <TodoList model={model.components.todoList} />
    </div>
  )
}

// src/steps/step-7-vue/TodoPage.vue
<script setup lang="ts">
import { TodoPageModel } from '../../models/TodoPageModel'
import TodoList from './TodoList.vue'

  const props = defineProps<{ model: TodoPageModel }>()
  const model = props.model
</script>

<template>
  <div>
    <p>Todo Page in Vue</p>
    <TodoList :model="model.components.todoList" />
  </div>
</template>
