// src/steps/step-6-react/TodoList.tsx
/** @jsx React.createElement */
import React, { useEffect } from 'react'
import { TodoListModel } from '../../models/TodoListModel'
import { useSignal } from './useSignal'

interface Props {
  model: TodoListModel
}
export function TodoList({ model }: Props) {
  const data = useSignal(model.data)
  useEffect(() => {
    model.getTodos()
  }, [])
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
      {data.state === 'initial' && <p>Waiting for data to be loaded</p>}
      {data.state === 'pending' && (
        <p>Loading…</p>
      )}
      {data.state === 'failure' && (
        <p>Error: {data.error.message}</p>
      )}
      {data.state === 'success' && (
        <ul>
          {data.value.map((todo) => (
            <li key={todo.id}>
              {todo.title}
            </li>
          ))}
        </ul>
      )}
    </div>
  )
}

// src/steps/step-7-vue/TodoList.vue
<script setup lang="ts">
import { onMounted } from 'vue'
import { TodoListModel } from '../../models/TodoListModel'
import { signalRef } from './signalRef'

  const props = defineProps<{ model: TodoListModel }>()
  const model = props.model

  const data = signalRef(model.data)
  onMounted(() => model.getTodos())
</script>

<template>
  <div style="display: flex; flex-direction: column; gap: 0.5rem">
    <p v-if="data.state === 'initial'">Waiting for data to be loaded</p>
    <p v-else-if="data.state === 'pending'">Loading…</p>
    <p v-else-if="data.state === 'failure'">
      Error: {{data.error.message}}
    </p>
    <ul v-else>
      <li v-for="todo in data.value">
        {{todo.title}}
      </li>
    </ul>
  </div>
</template>
