// src/spa-client-side/9-toggle-todo/vue/App.vue
<script setup lang="ts">
import { signalRef } from '@/spa-client-side/7-vue-app/signalRef'
import { AppModel } from '../AppModel'
import TodoPage from './TodoPage.vue'

const props = defineProps<{ model: AppModel }>()
const model = props.model

const route = signalRef(model.route)
</script>

<template>
  <h2>Vue App</h2>
  <p v-if="route.name === 'NotFound'">
    Page Not Found
    <button type="button" @click="model.goToTodos">Go to todos</button>
  </p>
  <TodoPage v-if="route.name === 'TodoListPage'" :model="route.make()" />
</template>

// src/spa-client-side/10-update-a-todo-title/react/App.tsx
/** @jsx React.createElement */
import React from 'react'
import { TodoPage } from './TodoPage'
import { useSignal } from '@/spa-client-side/6-react-app/useSignal'
import { AppModel } from '../AppModel'

interface Props {
  model: AppModel
}

export function App({ model }: Props) {
  const route = useSignal(model.route)

  return (
    <div>
      <h2>React App</h2>
      {route.name === 'NotFound' && (
        <p>
          {'Page Not Found '}
          <button type="button" onClick={model.goToTodos}>
            {'Go to todos'}
          </button>
        </p>
      )}
      {route.name === 'TodoListPage' && <TodoPage model={route.make()} />}
    </div>
  )
}
