// src/spa-client-side/10-update-a-todo-title/vue/TodoPage.vue
<script setup lang="ts">
import { onMounted, onUnmounted } from 'vue'
import { signalRef } from '@/spa-client-side/7-vue-app/signalRef'
import TodoCheckboxList from './TodoCheckboxList.vue'
import { TodoPageModel } from '../TodoPageModel'
import RemoteData from '@/spa-client-side/7-vue-app/RemoteData.vue'

const props = defineProps<{ model: TodoPageModel }>()
const model = props.model

const todoList = signalRef(model.getTodoList.data)
const canPatchAnyTodo = signalRef(model.canPatchAnyTodo)

// fetch the todos on mount.
onMounted(() => void model.getTodoList.trigger())

onUnmounted(model.dispose)
</script>

<template>
  <div>
    <p>Todo Page in Vue</p>
    <RemoteData :data="todoList">
      <template #success="{ value }">
        <TodoCheckboxList
          :todos="value"
          :disabled="!canPatchAnyTodo"
          @toggle="model.toggleTodo"
          @title-changed="model.changeTodoTitle"
        />
      </template>
    </RemoteData>
  </div>
</template>

// src/spa-client-side/10-update-a-todo-title/react/TodoPage.tsx
/** @jsx React.createElement */
import React from 'react'
import { RemoteData } from '@/spa-client-side/6-react-app/RemoteData'
import { useSignal } from '@/spa-client-side/6-react-app/useSignal'
import { useEffect } from 'react'
import { TodoPageModel } from '../TodoPageModel'
import { TodoCheckboxList } from './TodoCheckboxList'

interface Props {
  model: TodoPageModel
}

export function TodoPage({ model }: Props) {
  const todoList = useSignal(model.getTodoList.data)
  const canPatchAnyTodo = useSignal(model.canPatchAnyTodo)

  // fetch the todo list on mount.
  useEffect(() => {
    void model.getTodoList.trigger()
    // explicitly mark the promise as non-awaited with `void`
  }, [])

  // dispose on unmount.
  useEffect(() => model.dispose, [])

  return (
    <div>
      <p>Todo Page in React</p>
      <RemoteData
        data={todoList}
        success={(todos) => (
          <TodoCheckboxList
            todos={todos}
            onToggle={model.toggleTodo}
            disabled={!canPatchAnyTodo}
            onTitleChanged={model.changeTodoTitle}
          />
        )}
      />
    </div>
  )
}
