// src/9-toggle-todo/vue/TodoPage.vue
<script setup lang="ts">
import { onMounted, onUnmounted } from 'vue'
import { signalRef } from '@/7-vue-app/signalRef'
import TodoCheckboxList from './TodoCheckboxList.vue'
import { TodoPageModel } from '../TodoPageModel'
import RemoteData from '@/7-vue-app/RemoteData.vue'

const props = defineProps<{ model: TodoPageModel }>()
const model = props.model

const todoList = signalRef(model.getTodoList.data)
const toggleData = signalRef(model.toggleTodo.data)

// fetch the todos on mount.
onMounted(() => void model.getTodoList.trigger())

onUnmounted(model.dispose)
</script>

<template>
  <div>
    <p>Todo Page in Vue</p>
    <RemoteData :data="todoList">
      <template #success="{ value }">
        <TodoCheckboxList
          :todos="value"
          :disabled="toggleData.state === 'pending'"
          @toggle="model.toggleTodo.trigger"
        />
      </template>
    </RemoteData>
  </div>
</template>

// src/9-toggle-todo/react/TodoPage.tsx
/** @jsx React.createElement */
import React from 'react'
import { RemoteData } from '@/6-react-app/RemoteData'
import { useSignal } from '@/6-react-app/useSignal'
import { useEffect } from "react"
import { TodoPageModel } from '../TodoPageModel'
import { TodoCheckboxList } from "./TodoCheckboxList"

interface Props {
  model: TodoPageModel
}

export function TodoPage({ model }: Props) {
  const todoList = useSignal(model.getTodoList.data)
  const toggleData = useSignal(model.toggleTodo.data)

  // fetch the todo list on mount.
  useEffect(() => {
    void model.getTodoList.trigger()
    // explicitly mark the promise as non-awaiting with `void`
  }, [])

  // dispose on unmount.
  useEffect(() => model.dispose, [])

  return (
    <div>
      <p>Todo Page in React</p>
      <RemoteData
        data={todoList}
        success={(todos) => (
          <TodoCheckboxList
            todos={todos}
            onToggle={model.toggleTodo.trigger}
            disabled={toggleData.state === 'pending'}
          />
        )}
      />
    </div>
  )
}
