// src/9-toggle-todo/vue/TodoCheckboxList.vue
<script setup lang="ts">
  import { Todo } from '@/setup/Api'

  const props = defineProps<{
    todos: Todo[]
    disabled: boolean
  }>()
  const emit = defineEmits<{
    toggle: [todo: Todo]
  }>()
</script>

<template>
  <div>
    <label v-for="todo in props.todos" style="display: block;">
      <input type="checkbox" :checked="todo.completed" :disabled="props.disabled" @change="emit('toggle', todo)" />
      <span>{{ todo.title }}</span>
    </label>
  </div>
</template>

// src/9-toggle-todo/react/TodoCheckboxList.tsx
/** @jsx React.createElement */
import React from "react"
import { Todo } from "../../setup/Api"

interface Props {
  todos: Todo[]
  onToggle: (todo: Todo) => unknown
  disabled: boolean
}
export function TodoCheckboxList({ todos, onToggle, disabled }: Props) {
  return (
    <div>
      {todos.map((todo) => (
        <label key={todo.id} style={{ display: 'block' }}>
          <input
            type="checkbox"
            checked={todo.completed}
            onChange={() => onToggle(todo)}
            disabled={disabled}
          />
          <span>{todo.title}</span>
        </label>
      ))}
    </div>
  )
}
