// src/11-delete-a-todo/react/ConfirmActionDialog.tsx
/** @jsx React.createElement */
import React from "react"
import { RemoteActionToConfirm } from "@/setup/RemoteActionToConfirm"
import { useSignal } from '@/6-react-app/useSignal'

interface Props<T, Args extends any[]> {
  action: RemoteActionToConfirm<T, Args>
  children: (...args: Args) => React.ReactNode
}

export function ConfirmActionDialog<T, Args extends any[]>({
  action,
  children,
}: Props<T, Args>) {
  const data = useSignal(action.data)
  const pendingApproval = useSignal(action.pendingApproval)

  return (
    <dialog open={!!pendingApproval}>
      <header>Confirm</header>

      <div>{pendingApproval && children(...pendingApproval)}</div>

      <footer>
        <button type="button" onClick={() => action.cancel()}>
          Cancel
        </button>

        <button
          type="button"
          onClick={() => action.confirm()}
          disabled={data.state === "pending"}
        >
          Confirm
        </button>
      </footer>
    </dialog>
  )
}

// src/11-delete-a-todo/vue/ConfirmActionDialog.vue
<script setup lang="ts" generic="T, Args extends any[]">
import { signalRef } from '@/7-vue-app/signalRef'
import { RemoteActionToConfirm } from '../RemoteActionToConfirm'

  const props = defineProps<{
    action: RemoteActionToConfirm<T, Args>
  }>()

  const pendingApproval = signalRef(props.action.pendingApproval)
  const data = signalRef(props.action.data)
</script>

<template>
  <dialog :open="!!pendingApproval">
    <header>Confirm</header>

    <slot v-if="pendingApproval" :value="pendingApproval"></slot>

    <footer>
      <button type="button" @click="() => action.cancel()">
        Cancel
      </button>

      <button
        type="button"
        @click="() => action.confirm()"
        :disabled="data.state === 'pending'"
      >
        Confirm
      </button>
    </footer>
  </dialog>
</template>
