// src/spa-client-side/9-toggle-todo/vue/TodoCheckboxList.vue
<script setup lang="ts">
import { Todo } from '@/spa-client-side/setup/TodoApi'

const props = defineProps<{
  todos: Todo[]
  disabled: boolean
}>()
const emit = defineEmits<{
  toggle: [todo: Todo]
}>()
</script>

<template>
  <div class="todo-item">
    <label v-for="todo in props.todos" style="display: block">
      <input
        type="checkbox"
        :checked="todo.completed"
        :disabled="props.disabled"
        @change="emit('toggle', todo)"
      />
      <span>{{ todo.title }}</span>
    </label>
  </div>
</template>

// src/spa-client-side/9-toggle-todo/react/TodoCheckboxList.tsx
/** @jsx React.createElement */
import React from 'react'
import { Todo } from '@/spa-client-side/setup/TodoApi'

interface Props {
  todos: Todo[]
  onToggle: (todo: Todo) => unknown
  disabled: boolean
}
export function TodoCheckboxList({ todos, onToggle, disabled }: Props) {
  return (
    <div>
      {todos.map((todo) => (
        <label key={todo.id} className="todo-item">
          <input
            type="checkbox"
            checked={todo.completed}
            onChange={() => onToggle(todo)}
            disabled={disabled}
          />
          <span>{todo.title}</span>
        </label>
      ))}
    </div>
  )
}
